### ISSUE TITLE
deparse_call_multi()

### ISSUE THREAD

**Issue by krlmlr** [cynkra/constructive#102]
We have a quadrangle with one missing vertex.

- `deparse_call_multi()` is to `deparse_call()` what `construct_multi()` is to `construct()`

- `deparse_call_multi()` is to `construct_mult()` what `deparse_call()` is to `construct()` 

Rationale: I'm working on "peeling off" layers from a stack of APIs, and I want to record expressions in an underlying API as a queue of named expressions. With `deparse_call_multi()` I'd get a styled equivalent script.

``` r
# What exists today
df <- mtcars[1:3, 1:3]
name <- rlang::sym("my_df")
constructive::construct_multi(rlang::list2(!!name := df))
#> my_df <- data.frame(
#>   mpg = c(21, 21, 22.8),
#>   cyl = c(6, 6, 4),
#>   disp = c(160, 160, 108),
#>   row.names = c("Mazda RX4", "Mazda RX4 Wag", "Datsun 710")
#> )

df_expr <- rlang::expr(mtcars[1:3, 1:3])
constructive::deparse_call(df_expr)
#> mtcars[1:3, 1:3]

# What I'm looking for:
constructive::deparse_call_multi(rlang::list2(!!name := df_expr))
#> Error: 'deparse_call_multi' is not an exported object from 'namespace:constructive'

# My current workaround:
paste0(name, " <- ", format(constructive::deparse_call(df_expr)))
#> [1] "my_df <- mtcars[1:3, 1:3]"
```

<sup>Created on 2023-03-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by moodymudskipper** [comment]
That's not hard to implement but harder to explain

* `construct()` is a better `dput()`
* `construct_multi()` as a better `dump()`
* `deparse_call()` is a better (albeit narrower) `deparse()` or `expr_deparse()`
* `deparse_call_multi()` is taking a named list of calls and outputs code that evaluates them and binds them to the provided names

Probably your quadrangle description can be in the doc with an example and we'll be fine. 
On the same doc file as deparse_call().

**Comment by krlmlr** [comment]
Perhaps:

> For completeness, we also provide `deparse_call_multi()` that combines (ideas from) `deparse_call()` with `construct_multi()` and may be useful in some cases.

Let's think about it, no need to rush the implementation.

**Comment by krlmlr** [comment]
I'm reworking the code where I'm using this, I no longer need this feature.
