### ISSUE TITLE
construct_recover

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/constructive#197]
Basically call `construct_multi()` on every env of the call stack, but there's a bit more to it.

I think maybe this template might work, we open an untitled script for each call and we have : 

```
local(
  envir = new.env(parent = constructive::env("....")),
  {
    browser()
    # commented parent_call(arg1=foo, ...) 
    arg1 <- ... 
    bar <- ...
    ...
    failing_call(bar, ...)
  }
)
```

We need to construct unevaluated promises with a proper delayedAssign() call at time of error.

The above might be evaluated and explored freely with ctrl + enter if environments don't matter, if they do we can execute the `local()` call and we'll browse with the right scope and will be able to reproduce the error.

cc @krlmlr

**Comment by krlmlr** [comment]
Do we need every env on the call stack, or only the function's environment with all parents?

**Comment by moodymudskipper** [comment]
In theory we need every frame to choose where we want to debug, and then every parent for each frame.

I think an absolutely general solution is too hard and impractical.

I suggest we use `options(error = recover)` choose the frame we want, and there we can run `construct_reprex()` which will construct the caller env and the sys.call(). I have a prototype that works pretty well already.

Closing this for now
