### ISSUE TITLE
Fallback for big objects

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/constructive#198]
Some objects might be a bit too big to be conveniently constructed with standard constructors.
Can we use the data arg for those ? If an element is too big, the containing object is necessarily too big too, unless the "too big" applies only to data frames for instance. So we need a mechanism for this, either a list of classes or a predicate function (the mos flexible approach).

Already works: 

``` r
foo <- list(
  a = data.frame(x = runif(10000), y = runif(10000)),
  b = 2,
  c = 3
)

constructive::construct(foo, data = list(A = foo[[1]]))
#> list(a = A, b = 2, c = 3)
```

<sup>Created on 2023-06-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Maybe something like:

```
constructive::construct(foo, store = ~ is.data.frame(.x) && obj.size(.x) > ...)
#> .STORE <- constructive::.store()
#> list(a = .STORE[[1]], b = 2, c = 3)
```

In the above `constructive::.store()` is reset for every new call to construct() but we can keep copies easily. 

cc @krlmlr

**Comment by moodymudskipper** [comment]
@krlmlr I think I opened this on your request, I'm tempted to close as it doesn't seem all that useful to me, do you have a use case ?

**Comment by krlmlr** [comment]
I had missed the `data` argument. How does it work -- `identical()`, or comparing SEXP addresses?

**Comment by moodymudskipper** [comment]
It uses `identical()`
