### ISSUE TITLE
roxygen2 import?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/constructive#264]
This mildly surprises me. What do we need it for?

**Comment by moodymudskipper** [comment]
We can probably move to Suggests.
I use roxygen2 to generate automatically the doc of ?construct so it refers to all opt_ functions.
For this I needed to define a custom tag so I have functions calling roxygen2 functions, triggered by `document()`

**Comment by krlmlr** [comment]
Interesting. Can you use `vctrs::s3_register()` ?
