### ISSUE TITLE
`deparse_call()` and options

### ISSUE THREAD

**Issue by krlmlr** [cynkra/constructive#294]
How can we pass options to `deparse_call()` ? I want the output to be `'"'` via `opts_atomic(escape = TRUE)` . Follow-up to #170?

``` r
constructive::deparse_call('"')
#> "\""
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by moodymudskipper** [comment]
We have in the code 

```
  if (rlang::is_syntactic_literal(call)) {
    return(.cstr_construct(call, template = NULL, data = NULL))
  }
```

We would just need to add the character parsing related args to it, namely `escape` and `unicode_representation`, and forward them there. However it seems that the `escape` feature was not properly tested and is broken so we'll need to fix that first (backslash escape hell :( )
