### ISSUE TITLE
add grouping to pkgdown reference index?

### ISSUE THREAD

**Issue by maelle** [cynkra/constructive#395]
:-)

**Comment by moodymudskipper** [comment]
I don't understand )-:

**Comment by maelle** [comment]
Sorry! I mean using https://pkgdown.r-lib.org/reference/build_reference.html#reference-index

so that https://cynkra.github.io/constructive/reference/index.html instead of being an alphabetically ordered list, would be grouped into categories, with the most important functions (`construct()` in particular) at the top.

**Comment by maelle** [comment]
The grouping (minus the typo see #443) looks great! :tada:

**Comment by moodymudskipper** [comment]
Thanks Maelle, it was an excellent suggestion!
