### ISSUE TITLE
hex logo?

### ISSUE THREAD

**Issue by luisDVA** [cynkra/constructive#478]
I have a constructive sticker (one with lego pieces) that I received from the cynkra booth at posit::conf 2024. I wanted to show others the hex logo but it's not in this repo. Does it live anywhere else?

**Comment by moodymudskipper** [comment]
Hi Luis! Thanks for your interest and sharing constructive with others. You're right, I forgot to add it to the repo! Let's keep this issue open and meanwhile here it is! 
![hex-constructive](https://github.com/user-attachments/assets/623216bc-be4c-4d0e-bbf5-8dccc74700d9)
