### ISSUE TITLE
Console message for `construct_clip()`?

### ISSUE THREAD

**Issue by wurli** [cynkra/constructive#486]
How would you feel about the idea of adding some console messages to `construct_clip()`? Currently there's nothing to signal to a user that anything about the global state has changed, which to me feels like a bit of a sharp edge. 

I'd suggest displaying the complete text of the copied code, e.g:

``` r
constructive::construct_clip(letters)
#> ℹ Construct code has been added to the clipboard:
#> ``` r
#> c(
#>   "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
#>   "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
#> )
#> ```
```

A more terse message might be something like `ℹ Added 4 lines to the clipboard`, but I think showing the full code is better.

Here's why I think more messaging would be useful:

* Since `construct_clip()` modifies the global state, it seems polite to notify the user. There's an interesting section about this in the WIP [tidy design principles](https://design.tidyverse.org/side-effects.html#make-side-effects-noisy).

* Sometimes I iterate through calls to `construct()`/`construct_clip()` a bit before I arrive at something I want to use. Iterating using `construct_clip()` is currently not much fun because you need to paste the results to see what they are, so IMO this would be a nice convenience feature.

Happy to make a PR if you like this idea.

I'm really enjoying this package! Thanks for creating/maintaining it 😃

**Comment by moodymudskipper** [comment]
This sounds good to me thanks! I'm happy to review a PR

**Comment by wurli** [comment]
Nice, thanks! Just putting one together now. I noticed that {prettycode} is required for syntax highlighting, but I think this can be removed in favour of `cli::code_highlight()` (introduced in cli 3.1.0) since cli is already a dependency. Happy for me to make that change as part of the same PR?

**Comment by wurli** [comment]
Nice one, will do 👍
